/**
 * Holds the list of scammer style quotes for the bot.
 */
object Quotes {
    val list = listOf(
        "Hello sir, I am calling you from Windows security center.",
        "Please do not hang up, your computer is sending us many errors.",
        "I am a certified technician from Microsoft support.",
        "Your IP address shows suspicious activity, we must fix it now.",
        "Kindly give me remote access so I can resolve the issue immediately.",
        "Do not worry, I will refund your money once we complete verification.",
        "This call is regarding your expired car warranty.",
        "You have been selected for a special government grant.",
        "Congratulations, you won a free iPhone, just pay the shipping fee.",
        "I need your banking details to confirm the transaction.",
        "Your account has been compromised, let us secure it for you.",
        "The IRS is filing a lawsuit against you unless you respond today.",
        "Our records show unpaid taxes; immediate payment is required.",
        "We detected a virus on your computer that could erase all data.",
        "This is Amazon security; there is a problem with your recent order.",
        "You qualify for a low-interest loan, no credit check required.",
        "If you do not cooperate, your internet will be disconnected.",
        "We have a special offer just for loyal customers like you.",
        "You must act fast to claim this limited-time prize.",
        "Sir, your Windows license key has expired, we need to renew it.",
        "I can see hackers are trying to access your email right now.",
        "To fix the issue, we will install a secure firewall on your system.",
        "Please stay on the line, do not speak to anyone else about this.",
        "There is a warrant issued in your name for suspicious activities.",
        "You should not share this with your family to avoid confusion.",
        "Our technician will guide you through each step carefully.",
        "This problem may spread to your online banking if left unresolved.",
        "We only charge a small fee for lifetime protection.",
        "Your router is sending out illegal signals, please cooperate.",
        "Keep your phone connected, otherwise the process will fail.",
        "I will help you purchase gift cards to resolve the balance.",
        "It is very urgent that you follow my instructions exactly.",
        "We have detected someone else using your social security number.",
        "The best way to secure your account is with our premium software.",
        "You are the lucky winner of a free vacation to Hawaii.",
        "Our system shows a refund is pending to your account.",
        "You must pay a processing fee before the refund can be issued.",
        "If you decline, we will have to disable your computer permanently.",
        "Please trust me, I have ten years of experience in this field.",
        "Your phone number was chosen from our exclusive database.",
        "We work directly with the government to stop these hackers.",
        "For verification, kindly state your full name and address.",
        "Once you buy the gift cards, read me the numbers on the back.",
        "Do not worry about the charges, they will be refunded quickly.",
        "We are monitoring your computer in real time for any threats.",
        "You do not want the authorities to get involved, do you?",
        "Our support plan includes a free lifetime upgrade.",
        "There is suspicious login activity from a foreign country.",
        "Please keep this conversation private to avoid further issues.",
        "We will clean your system of all viruses right away.",
        "Your firewall has been turned off by hackers.",
        "Only I have the authorization code to reactivate it.",
        "This is the last chance before your account is locked.",
        "I will personally handle your case until it is solved.",
        "We just need a small deposit to confirm your identity.",
        "Act now or the offer will expire within the next hour.",
        "Your bank flagged a suspicious transaction from overseas.",
        "If you ignore this call, you may lose all your data.",
        "I can see your computer is running very slowly due to malware.",
        "Our premium package will keep you safe for five years.",
        "Trust me, this is the only way to protect your network.",
        "We guarantee your money back if you are not satisfied.",
        "The police may arrive at your doorstep if you do not comply.",
        "We already charged your card; we just need confirmation.",
        "By staying on the call, you accept our terms and conditions.",
        "You are under investigation for illegal online activities.",
        "Do not panic, we can fix everything quickly.",
        "Your antivirus subscription has expired today.",
        "I can offer you a huge discount if you sign up right now.",
        "Remember, hackers never sleep, and neither do we.",
        "Our service center received multiple alerts from your device.",
        "This conversation is recorded for quality assurance.",
        "You may be eligible for compensation from a recent data breach.",
        "You must provide remote access so we can verify the problem.",
        "Our tools will scan your computer for illegal downloads.",
        "If you disconnect, your system will remain vulnerable.",
        "I am seeing ransomware files on your desktop at this very moment.",
        "The network team will charge extra if we do not act today.",
        "You should not trust other callers claiming to be from support.",
        "We can fix the issue in under 30 minutes, guaranteed.",
        "Your voice sounds worried, but I assure you everything is fine.",
        "The hacking attempts appear to come from your local area.",
        "I need you to follow some simple steps on your keyboard.",
        "Once we connect, you will see the problem yourself.",
        "There is a hold on your bank account for security reasons.",
        "Only our certificate can remove the malicious files.",
        "We will update your drivers to prevent future attacks.",
        "Your personal information is safe with us, I promise.",
        "The security code I provide must remain confidential.",
        "I can extend your warranty for a very low price today.",
        "Our specialists are all certified by major tech companies.",
        "This emergency session normally costs much more.",
        "You do not need to visit any store, we handle it all remotely.",
        "Just grab a pen and write down this important reference number.",
        "We appreciate your patience during this critical process.",
        "After this, your system will be faster than ever before.",
        "It is highly unusual to see so many errors from one computer.",
        "You have reached the priority support line.",
        "We will send you a confirmation email once the case is resolved.",
        "Please cooperate fully to avoid additional charges.",
        "Hackers are trying to steal your identity as we speak.",
        "Our records show you recently purchased online security.",
        "I am obligated to warn you about the legal consequences.",
        "Let us start a quick scan to check for hidden spyware.",
        "Many customers ignore this warning and regret it later.",
        "Your service provider authorized us to assist you.",
        "We have limited slots left for this exclusive offer.",
        "The refund will be processed as soon as we verify your details.",
        "This method is 100% safe and approved by our experts.",
        "Thank you for trusting us with your computer today.",
        "Stay connected and we will guide you every step of the way.",
        "We just found another problem that needs urgent attention.",
        "The hackers are watching everything you do online.",
        "I will stay with you on the line until it is completely fixed.",
        "You have qualified for a major security upgrade at no cost.",
        "I assure you, thousands of customers use this service daily.",
        "Once we are done, you will receive a confirmation text message.",
        "Your quick response today will keep your accounts safe.",
        "Kindly update your payment information to avoid interruption.",
        "If you end the call, the process will reset and take longer.",
        "We can remove all hackers within minutes using our tools.",
        "You should not delay, the threat level is increasing rapidly.",
        "Our team is the only one authorized to handle such cases.",
        "Once payment is verified, we will send you the license key.",
        "Please turn on your computer so we can begin immediately.",
        "Every moment you wait, more data could be stolen.",
        "We value your trust, and that is why we work so diligently." 
    )
}
